baseURL = 'https://www.atharvapandey.com/'
languageCode = 'en-us'
title = 'Atharva'
theme = 'github-style'
copyright = "Copyright © 2024 Atharva Pandey"
enableRobotsTXT = true

[minify]
disableCSS = false
disableHTML = false
disableSVG = false
disableJSON = false
disableXML = false
disableJS = false
