baseURL="https://atharvapandey.com/"
languageCode="en-us"
title="Atharva's blog"
theme="github-style"
googleAnalytics="UA-123456-789"
pygmentsCodeFences=true
pygmentsUseClasses=true

[params]
author="Atharva Pandey"
description="I code, build, architect and drink coffee, decaf is BS."
github="Gopherine"
twitter="vedaatharva"
linkedin="atharvapandey"
email="atharvajava@gmail.com"
url="https://atharvapandey.com"
keywords="blog, google analytics, rust, golang, javascript, react, typescript, software architecture"
rss=true
lastmod=true
favicon="/images/nerd-crab.ico"
avatar="/images/avatar.webp"
headerIcon="/images/nerdy-crab-light.webp"
location="India"
userStatusEmoji="☕"

[params.giscus]
repo="gopherine/hugo-blog"
repoId="R_kgDOLTrS1w"
category="Announcements"
category-id="DIC_kwDOLTrS184CdYrP"
mapping="title"
strict="0"
reactions-enabled="1"
emitMetadata="0"
inputPosition="bottom"
theme="preferred_color_scheme"
lang="en"
loading="lazy"
crossorigin="anonymous"

[frontmatter]
lastmod=["lastmod", ":fileModTime", ":default"]
