name: Hugo Build

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The type of runner that the job will run on

    steps:
    - uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
      node-version: '18'  # Use the Node.js version that matches your development environment

    - name: Install Dependencies
      run: npm install

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: npm run build  # Runs the Hugo build command
      env:
        NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}
        TINA_TOKEN: ${{ secrets.TINA_TOKEN }}

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Vercel token for authentication
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  # Vercel Organization ID
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # Vercel Project ID
        vercel-args: '--prod'  # Deploy to production
        working-directory: ./public  # Directory to deploy
